services:
  - type: web
    name: bakegenie
    env: python
    buildCommand: chmod +x .renderbuild.sh && ./.renderbuild.sh
    startCommand: source .venv/bin/activate && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PIP_NO_BUILD_ISOLATION
        value: "true"
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
