services:
  - type: web
    name: bakegenie
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 120 --max-requests 1000 --max-requests-jitter 50 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: max_split_size_mb:512
    healthCheckPath: /health
    autoDeploy: true
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 4GB
      cpu: 2
