"""
Create a sample dataset of common baking recipes
"""

import sqlite3
import os
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Sample recipes
SAMPLE_RECIPES = [
    {
        'name': 'Classic Chocolate Chip Cookies',
        'description': 'Soft and chewy cookies loaded with chocolate chips',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.25, 'unit': 'cups'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Pure Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Baking Soda', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Semi Sweet Chocolate Chips', 'amount': 2, 'unit': 'cups'}
        ],
        'instructions': '1. Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.\n2. Cream together butter and sugars until light and fluffy.\n3. Beat in eggs one at a time, then stir in vanilla.\n4. Whisk together flour, baking soda, and salt. Gradually mix into butter mixture.\n5. Stir in chocolate chips.\n6. Drop rounded tablespoons of dough onto prepared baking sheets.\n7. Bake for 10-12 minutes or until edges are lightly browned.\n8. Let cool on baking sheets for 5 minutes before transferring to wire racks.',
        'prep_time': 20,
        'cook_time': 12,
        'total_time': 32,
        'servings': 24,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 150,
        'protein': 2,
        'carbs': 19,
        'fat': 8,
        'fiber': 1,
        'sugar': 12,
        'rating': 4.8,
        'review_count': 1250
    },
    {
        'name': 'Classic Vanilla Cake',
        'description': 'Light and fluffy vanilla cake perfect for any occasion',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Cake Flour', 'amount': 3, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 2, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Pure Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Whole Milk', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n2. Whisk together flour, baking powder, and salt.\n3. Cream butter and sugar until light and fluffy.\n4. Add eggs one at a time, beating well after each addition.\n5. Stir in vanilla extract.\n6. Gradually add flour mixture alternating with milk.\n7. Pour batter into prepared pans.\n8. Bake for 30-35 minutes or until a toothpick comes out clean.\n9. Cool in pans for 10 minutes before removing to wire racks.',
        'prep_time': 30,
        'cook_time': 35,
        'total_time': 65,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 320,
        'protein': 5,
        'carbs': 45,
        'fat': 14,
        'fiber': 1,
        'sugar': 26,
        'rating': 4.7,
        'review_count': 850
    },
    {
        'name': 'Homemade Sourdough Bread',
        'description': 'Artisanal sourdough bread with a crispy crust and chewy interior',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Sourdough Starter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Warm Water', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Salt', 'amount': 2, 'unit': 'teaspoons'}
        ],
        'instructions': '1. Mix flour, starter, water, and salt until well combined.\n2. Knead for 10 minutes until smooth and elastic.\n3. Place in a greased bowl, cover, and let rise for 4-6 hours.\n4. Shape into a loaf and place in a proofing basket.\n5. Refrigerate overnight for 8-12 hours.\n6. Preheat oven with Dutch oven to 450°F (230°C).\n7. Score the bread and bake covered for 30 minutes.\n8. Remove lid and bake for additional 15-20 minutes until golden brown.\n9. Cool completely before slicing.',
        'prep_time': 360,
        'cook_time': 50,
        'total_time': 410,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'European',
        'meal_type': 'Bread',
        'calories': 120,
        'protein': 4,
        'carbs': 23,
        'fat': 0.5,
        'fiber': 1,
        'sugar': 0,
        'rating': 4.9,
        'review_count': 650
    },
    {
        'name': 'Fudgy Chocolate Brownies',
        'description': 'Rich and fudgy brownies with a crackly top',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Dark Chocolate', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Granulated Sugar', 'amount': 2, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Pure Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'All Purpose Flour', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cocoa Powder', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Preheat oven to 350°F (175°C). Line a 9x13 inch pan with parchment paper.\n2. Melt butter and chocolate together in a double boiler.\n3. Whisk in sugar until well combined.\n4. Add eggs one at a time, then stir in vanilla.\n5. Fold in flour, cocoa powder, and salt until just combined.\n6. Pour into prepared pan.\n7. Bake for 30-35 minutes until a toothpick comes out with moist crumbs.\n8. Cool completely before cutting into squares.',
        'prep_time': 20,
        'cook_time': 35,
        'total_time': 55,
        'servings': 24,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 180,
        'protein': 3,
        'carbs': 24,
        'fat': 9,
        'fiber': 2,
        'sugar': 18,
        'rating': 4.9,
        'review_count': 980
    },
    {
        'name': 'Buttery Croissants',
        'description': 'Flaky and buttery French croissants',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Warm Milk', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Cold Unsalted Butter', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Large Egg', 'amount': 1, 'unit': 'whole'}
        ],
        'instructions': '1. Mix flour, yeast, sugar, salt, and warm milk to form a dough.\n2. Knead for 10 minutes until smooth.\n3. Chill dough for 1 hour.\n4. Roll out dough and encase cold butter.\n5. Perform 3 letter folds with 1-hour chilling between each.\n6. Roll out and cut into triangles.\n7. Roll up triangles and shape into crescents.\n8. Proof for 2 hours.\n9. Brush with egg wash.\n10. Bake at 400°F (200°C) for 20-25 minutes until golden brown.',
        'prep_time': 360,
        'cook_time': 25,
        'total_time': 385,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'French',
        'meal_type': 'Bread',
        'calories': 280,
        'protein': 5,
        'carbs': 28,
        'fat': 17,
        'fiber': 1,
        'sugar': 3,
        'rating': 4.8,
        'review_count': 420
    },
    {
        'name': 'Banana Walnut Bread',
        'description': 'Moist and flavorful banana bread loaded with walnuts',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Ripe Bananas', 'amount': 3, 'unit': 'large'},
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Soda', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Chopped Walnuts', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Preheat oven to 350°F. Grease a 9x5 inch loaf pan.\n2. Mash bananas in a large bowl.\n3. Mix in melted butter, brown sugar, eggs, and vanilla.\n4. Stir in flour, baking soda, and salt until just combined.\n5. Fold in chopped walnuts.\n6. Pour into prepared pan.\n7. Bake for 60-65 minutes until a toothpick comes out clean.\n8. Cool in pan for 10 minutes before removing.',
        'prep_time': 15,
        'cook_time': 65,
        'total_time': 80,
        'servings': 12,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Bread',
        'calories': 220,
        'protein': 4,
        'carbs': 28,
        'fat': 11,
        'fiber': 2,
        'sugar': 15,
        'rating': 4.7,
        'review_count': 890
    },
    {
        'name': 'French Baguettes',
        'description': 'Classic French bread with a crispy crust and soft interior',
        'dietary': 'Vegetarian',  # No meat products
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Warm Water', 'amount': 1.5, 'unit': 'cups'}
        ],
        'instructions': '1. Mix flour, yeast, and salt.\n2. Add warm water and knead for 10 minutes.\n3. Let rise for 1 hour.\n4. Divide into 2-3 portions and shape into baguettes.\n5. Let rise again for 30 minutes.\n6. Score the tops and spray with water.\n7. Bake at 450°F for 25 minutes with steam.',
        'prep_time': 120,
        'cook_time': 25,
        'total_time': 145,
        'servings': 3,
        'difficulty': 'Medium',
        'cuisine_type': 'French',
        'meal_type': 'Bread',
        'calories': 130,
        'protein': 4,
        'carbs': 26,
        'fat': 0.5,
        'fiber': 1,
        'sugar': 0,
        'rating': 4.6,
        'review_count': 450
    },
    {
        'name': 'Blueberry Muffins',
        'description': 'Tender muffins bursting with fresh blueberries',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Milk', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Fresh Blueberries', 'amount': 1.5, 'unit': 'cups'}
        ],
        'instructions': '1. Preheat oven to 375°F. Line a 12-cup muffin tin.\n2. Whisk flour, baking powder, and salt.\n3. Cream butter and sugar until light.\n4. Beat in eggs and vanilla.\n5. Alternate adding flour mixture and milk.\n6. Fold in blueberries.\n7. Divide batter among muffin cups.\n8. Bake for 20-25 minutes.',
        'prep_time': 20,
        'cook_time': 25,
        'total_time': 45,
        'servings': 12,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Breakfast',
        'calories': 180,
        'protein': 3,
        'carbs': 25,
        'fat': 8,
        'fiber': 1,
        'sugar': 14,
        'rating': 4.7,
        'review_count': 780
    },
    {
        'name': 'Apple Pie',
        'description': 'Classic double-crust apple pie with cinnamon and nutmeg',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.5, 'unit': 'cups'},
            {'name': 'Cold Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Ice Water', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Granny Smith Apples', 'amount': 6, 'unit': 'large'},
            {'name': 'Granulated Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Ground Nutmeg', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Lemon Juice', 'amount': 1, 'unit': 'tablespoon'}
        ],
        'instructions': '1. Make pie dough and chill for 1 hour.\n2. Peel and slice apples, mix with sugar and spices.\n3. Roll out dough and line pie dish.\n4. Fill with apple mixture.\n5. Top with second crust, crimp edges, cut vents.\n6. Bake at 425°F for 45 minutes until golden.',
        'prep_time': 45,
        'cook_time': 45,
        'total_time': 90,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 320,
        'protein': 3,
        'carbs': 45,
        'fat': 16,
        'fiber': 3,
        'sugar': 25,
        'rating': 4.8,
        'review_count': 950
    },
    {
        'name': 'Cinnamon Rolls',
        'description': 'Soft and fluffy rolls with cinnamon-sugar filling and cream cheese frosting',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Warm Milk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Ground Cinnamon', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Brown Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Cream Cheese', 'amount': 4, 'unit': 'ounces'},
            {'name': 'Powdered Sugar', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Make dough with flour, yeast, milk, sugar, butter, eggs.\n2. Let rise until doubled.\n3. Roll out and spread with butter, cinnamon, brown sugar.\n4. Roll up and cut into 12 rolls.\n5. Let rise again.\n6. Bake at 375°F for 20-25 minutes.\n7. Top with cream cheese frosting.',
        'prep_time': 180,
        'cook_time': 25,
        'total_time': 205,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Breakfast',
        'calories': 310,
        'protein': 5,
        'carbs': 48,
        'fat': 12,
        'fiber': 1,
        'sugar': 28,
        'rating': 4.9,
        'review_count': 1100
    },
    {
        'name': 'Lemon Pound Cake',
        'description': 'Rich and moist pound cake with fresh lemon flavor',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 3, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 2, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 6, 'unit': 'whole'},
            {'name': 'Lemon Zest', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Lemon Juice', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Milk', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Preheat oven to 325°F. Grease and flour a 12-cup bundt pan.\n2. Mix flour, baking powder, and salt.\n3. Cream butter and sugar until light and fluffy.\n4. Add eggs one at a time.\n5. Add lemon zest, juice, and vanilla.\n6. Alternate adding flour mixture and milk.\n7. Pour into pan and bake for 1 hour and 15 minutes.',
        'prep_time': 30,
        'cook_time': 75,
        'total_time': 105,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 380,
        'protein': 6,
        'carbs': 48,
        'fat': 19,
        'fiber': 1,
        'sugar': 32,
        'rating': 4.7,
        'review_count': 650
    },
    {
        'name': 'Chocolate Eclairs',
        'description': 'Light and airy choux pastry filled with vanilla cream and topped with chocolate',
        'ingredients': [
            {'name': 'Water', 'amount': 1, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'All Purpose Flour', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Whole Milk', 'amount': 2, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Cornstarch', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Vanilla Bean', 'amount': 1, 'unit': 'whole'},
            {'name': 'Dark Chocolate', 'amount': 6, 'unit': 'ounces'},
            {'name': 'Heavy Cream', 'amount': 0.5, 'unit': 'cup'}
        ],
        'instructions': '1. Make choux pastry with water, butter, flour, eggs.\n2. Pipe into 4-inch lengths.\n3. Bake at 400°F for 30 minutes.\n4. Make vanilla pastry cream.\n5. Fill eclairs with cream.\n6. Top with chocolate ganache.',
        'prep_time': 60,
        'cook_time': 30,
        'total_time': 90,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'French',
        'meal_type': 'Dessert',
        'calories': 280,
        'protein': 5,
        'carbs': 28,
        'fat': 17,
        'fiber': 1,
        'sugar': 15,
        'rating': 4.8,
        'review_count': 320
    },
    {
        'name': 'Oatmeal Raisin Cookies',
        'description': 'Chewy oatmeal cookies loaded with raisins and warm spices',
        'ingredients': [
            {'name': 'Old Fashioned Oats', 'amount': 3, 'unit': 'cups'},
            {'name': 'All Purpose Flour', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Baking Soda', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Raisins', 'amount': 1.5, 'unit': 'cups'}
        ],
        'instructions': '1. Preheat oven to 350°F.\n2. Mix oats, flour, cinnamon, baking soda, salt.\n3. Cream butter and sugars.\n4. Beat in eggs and vanilla.\n5. Stir in dry ingredients and raisins.\n6. Drop by rounded tablespoons onto baking sheets.\n7. Bake for 10-12 minutes.',
        'prep_time': 20,
        'cook_time': 12,
        'total_time': 32,
        'servings': 36,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 120,
        'protein': 2,
        'carbs': 18,
        'fat': 5,
        'fiber': 1,
        'sugar': 10,
        'rating': 4.6,
        'review_count': 890
    },
    {
        'name': 'Raspberry Danish',
        'description': 'Flaky Danish pastry filled with cream cheese and fresh raspberries',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Cold Unsalted Butter', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Cold Milk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Cream Cheese', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Fresh Raspberries', 'amount': 2, 'unit': 'cups'},
            {'name': 'Powdered Sugar', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Make Danish dough with flour, yeast, sugar, salt, butter, milk, egg.\n2. Chill and fold several times.\n3. Roll out and cut into squares.\n4. Fill with cream cheese and raspberries.\n5. Shape into diamonds.\n6. Let rise.\n7. Bake at 400°F for 20 minutes.\n8. Drizzle with glaze.',
        'prep_time': 180,
        'cook_time': 20,
        'total_time': 200,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'Danish',
        'meal_type': 'Breakfast',
        'calories': 320,
        'protein': 6,
        'carbs': 34,
        'fat': 18,
        'fiber': 2,
        'sugar': 16,
        'rating': 4.8,
        'review_count': 280
    },
    {
        'name': 'Carrot Cake',
        'description': 'Moist spiced cake with fresh carrots and cream cheese frosting',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Soda', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Ground Cinnamon', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Vegetable Oil', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Grated Carrots', 'amount': 3, 'unit': 'cups'},
            {'name': 'Chopped Walnuts', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cream Cheese', 'amount': 16, 'unit': 'ounces'},
            {'name': 'Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Powdered Sugar', 'amount': 4, 'unit': 'cups'}
        ],
        'instructions': '1. Preheat oven to 350°F. Grease two 9-inch cake pans.\n2. Mix flour, baking soda, cinnamon, salt.\n3. Whisk oils and sugars.\n4. Beat in eggs and vanilla.\n5. Stir in carrots and nuts.\n6. Bake for 30-35 minutes.\n7. Make cream cheese frosting.\n8. Frost cooled cake.',
        'prep_time': 30,
        'cook_time': 35,
        'total_time': 65,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 450,
        'protein': 6,
        'carbs': 58,
        'fat': 24,
        'fiber': 2,
        'sugar': 42,
        'rating': 4.9,
        'review_count': 1200
    },
    {
        'name': 'Focaccia Bread',
        'description': 'Italian olive oil bread with herbs and sea salt',
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Warm Water', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Olive Oil', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Sea Salt', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Fresh Rosemary', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Cherry Tomatoes', 'amount': 1, 'unit': 'cup'},
            {'name': 'Garlic', 'amount': 4, 'unit': 'cloves'}
        ],
        'instructions': '1. Mix flour, yeast, water, and oil.\n2. Knead until smooth.\n3. Let rise for 1 hour.\n4. Press into oiled pan.\n5. Top with herbs, tomatoes, garlic.\n6. Let rise again.\n7. Dimple surface and drizzle with oil.\n8. Bake at 425°F for 20-25 minutes.',
        'prep_time': 120,
        'cook_time': 25,
        'total_time': 145,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'Italian',
        'meal_type': 'Bread',
        'calories': 180,
        'protein': 4,
        'carbs': 26,
        'fat': 7,
        'fiber': 1,
        'sugar': 0,
        'rating': 4.7,
        'review_count': 580
    },
    {
        'name': 'Red Velvet Cupcakes',
        'description': 'Classic red velvet cupcakes with cream cheese frosting',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.5, 'unit': 'cups'},
            {'name': 'Cocoa Powder', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Baking Soda', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Vegetable Oil', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Red Food Coloring', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Buttermilk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cream Cheese', 'amount': 16, 'unit': 'ounces'},
            {'name': 'Powdered Sugar', 'amount': 4, 'unit': 'cups'}
        ],
        'instructions': '1. Preheat oven to 350°F. Line cupcake pans.\n2. Mix dry ingredients.\n3. Cream butter, oil, and sugar.\n4. Add eggs, coloring, vanilla.\n5. Alternate flour and buttermilk.\n6. Fill cupcake liners.\n7. Bake for 18-20 minutes.\n8. Top with cream cheese frosting.',
        'prep_time': 30,
        'cook_time': 20,
        'total_time': 50,
        'servings': 24,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 280,
        'protein': 3,
        'carbs': 38,
        'fat': 14,
        'fiber': 0,
        'sugar': 28,
        'rating': 4.8,
        'review_count': 950
    },
    {
        'name': 'Almond Biscotti',
        'description': 'Crunchy Italian cookies perfect for dipping in coffee',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.25, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Almond Extract', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Whole Almonds', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Preheat oven to 350°F.\n2. Mix flour, baking powder, salt.\n3. Cream butter and sugar.\n4. Beat in eggs and extracts.\n5. Stir in flour mixture and almonds.\n6. Shape into logs.\n7. Bake 25 minutes.\n8. Slice and bake again until crisp.',
        'prep_time': 25,
        'cook_time': 40,
        'total_time': 65,
        'servings': 24,
        'difficulty': 'Medium',
        'cuisine_type': 'Italian',
        'meal_type': 'Dessert',
        'calories': 120,
        'protein': 3,
        'carbs': 15,
        'fat': 6,
        'fiber': 1,
        'sugar': 7,
        'rating': 4.6,
        'review_count': 420
    },
    {
        'name': 'Chocolate Mousse Cake',
        'description': 'Decadent chocolate cake layered with rich chocolate mousse',
        'ingredients': [
            {'name': 'Dark Chocolate', 'amount': 12, 'unit': 'ounces'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 6, 'unit': 'whole'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'All Purpose Flour', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cocoa Powder', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Heavy Cream', 'amount': 2, 'unit': 'cups'},
            {'name': 'Espresso Powder', 'amount': 1, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Make chocolate cake layers.\n2. Prepare chocolate mousse.\n3. Layer cake with mousse.\n4. Chill until set.\n5. Cover with chocolate ganache.',
        'prep_time': 60,
        'cook_time': 30,
        'total_time': 90,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'French',
        'meal_type': 'Dessert',
        'calories': 450,
        'protein': 7,
        'carbs': 42,
        'fat': 32,
        'fiber': 3,
        'sugar': 35,
        'rating': 4.9,
        'review_count': 780
    },
    {
        'name': 'Pumpkin Pie',
        'description': 'Classic spiced pumpkin pie with flaky crust',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Cold Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Ice Water', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Pumpkin Puree', 'amount': 15, 'unit': 'ounces'},
            {'name': 'Evaporated Milk', 'amount': 12, 'unit': 'ounces'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Ground Cinnamon', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Ground Ginger', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Ground Nutmeg', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Granulated Sugar', 'amount': 0.75, 'unit': 'cup'}
        ],
        'instructions': '1. Make pie crust and chill.\n2. Mix pumpkin, milk, eggs, spices, sugar.\n3. Roll out crust and fit into pie dish.\n4. Pour filling into crust.\n5. Bake at 425°F for 15 minutes.\n6. Reduce to 350°F and bake 40-50 minutes more.',
        'prep_time': 30,
        'cook_time': 65,
        'total_time': 95,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 280,
        'protein': 6,
        'carbs': 34,
        'fat': 14,
        'fiber': 2,
        'sugar': 21,
        'rating': 4.7,
        'review_count': 890
    },
    {
        'name': 'Peach Cobbler',
        'description': 'Sweet peaches topped with buttery biscuit crust',
        'ingredients': [
            {'name': 'Fresh Peaches', 'amount': 8, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Lemon Juice', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Ground Cinnamon', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Cold Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Milk', 'amount': 0.5, 'unit': 'cup'}
        ],
        'instructions': '1. Toss peaches with sugar, lemon, cinnamon.\n2. Make biscuit topping.\n3. Pour peaches into baking dish.\n4. Top with biscuit dough.\n5. Bake at 375°F for 45-50 minutes.',
        'prep_time': 30,
        'cook_time': 50,
        'total_time': 80,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 320,
        'protein': 4,
        'carbs': 52,
        'fat': 12,
        'fiber': 3,
        'sugar': 36,
        'rating': 4.8,
        'review_count': 560
    },
    {
        'name': 'Challah Bread',
        'description': 'Traditional Jewish braided egg bread',
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Warm Water', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Vegetable Oil', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Honey', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 1.5, 'unit': 'teaspoons'}
        ],
        'instructions': '1. Proof yeast in warm water.\n2. Mix eggs, oil, honey.\n3. Add flour and salt.\n4. Knead until smooth.\n5. Let rise until doubled.\n6. Braid dough.\n7. Let rise again.\n8. Brush with egg wash.\n9. Bake at 350°F for 30-35 minutes.',
        'prep_time': 180,
        'cook_time': 35,
        'total_time': 215,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'Jewish',
        'meal_type': 'Bread',
        'calories': 190,
        'protein': 6,
        'carbs': 32,
        'fat': 5,
        'fiber': 1,
        'sugar': 4,
        'rating': 4.8,
        'review_count': 420
    },
    {
        'name': 'Lemon Meringue Pie',
        'description': 'Tangy lemon curd topped with fluffy meringue',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Cold Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Ice Water', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Cornstarch', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Large Egg Yolks', 'amount': 4, 'unit': 'whole'},
            {'name': 'Lemon Juice', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Lemon Zest', 'amount': 2, 'unit': 'tablespoons'},
            {'name': 'Large Egg Whites', 'amount': 4, 'unit': 'whole'},
            {'name': 'Cream of Tartar', 'amount': 0.5, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Make and blind bake pie crust.\n2. Cook lemon filling until thickened.\n3. Pour into crust.\n4. Make meringue.\n5. Top pie with meringue.\n6. Bake at 350°F until golden.',
        'prep_time': 45,
        'cook_time': 35,
        'total_time': 80,
        'servings': 8,
        'difficulty': 'Hard',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 310,
        'protein': 5,
        'carbs': 48,
        'fat': 12,
        'fiber': 0,
        'sugar': 36,
        'rating': 4.7,
        'review_count': 680
    },
    {
        'name': 'Tiramisu Cake',
        'description': 'Italian coffee-flavored layer cake with mascarpone cream',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Strong Coffee', 'amount': 1, 'unit': 'cup'},
            {'name': 'Mascarpone Cheese', 'amount': 16, 'unit': 'ounces'},
            {'name': 'Heavy Cream', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cocoa Powder', 'amount': 0.25, 'unit': 'cup'}
        ],
        'instructions': '1. Make vanilla cake layers.\n2. Soak layers with coffee.\n3. Make mascarpone filling.\n4. Layer cake with filling.\n5. Dust with cocoa powder.',
        'prep_time': 45,
        'cook_time': 30,
        'total_time': 75,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'Italian',
        'meal_type': 'Dessert',
        'calories': 420,
        'protein': 8,
        'carbs': 38,
        'fat': 28,
        'fiber': 1,
        'sugar': 26,
        'rating': 4.8,
        'review_count': 650
    },
    {
        'name': 'Danish Butter Cookies',
        'description': 'Crisp and buttery cookies perfect for gifting',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 3.5, 'unit': 'cups'},
            {'name': 'Unsalted Butter', 'amount': 1, 'unit': 'pound'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Cream butter and sugar.\n2. Beat in eggs and vanilla.\n3. Mix in flour and salt.\n4. Pipe into shapes.\n5. Bake at 350°F for 12-15 minutes.',
        'prep_time': 30,
        'cook_time': 15,
        'total_time': 45,
        'servings': 48,
        'difficulty': 'Medium',
        'cuisine_type': 'Danish',
        'meal_type': 'Dessert',
        'calories': 90,
        'protein': 1,
        'carbs': 8,
        'fat': 6,
        'fiber': 0,
        'sugar': 4,
        'rating': 4.7,
        'review_count': 480
    },
    {
        'name': 'Chocolate Babka',
        'description': 'Twisted bread filled with chocolate and streusel',
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Granulated Sugar', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 3, 'unit': 'whole'},
            {'name': 'Milk', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Dark Chocolate', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Cocoa Powder', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Make enriched dough.\n2. Let rise until doubled.\n3. Make chocolate filling.\n4. Roll out and spread filling.\n5. Twist into loaf.\n6. Let rise again.\n7. Bake at 350°F for 45-50 minutes.',
        'prep_time': 180,
        'cook_time': 50,
        'total_time': 230,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'Jewish',
        'meal_type': 'Bread',
        'calories': 320,
        'protein': 6,
        'carbs': 42,
        'fat': 16,
        'fiber': 2,
        'sugar': 18,
        'rating': 4.9,
        'review_count': 380
    },
    {
        'name': 'Fruit Scones',
        'description': 'Buttery British scones with dried fruit',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 3, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Cold Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Milk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Egg', 'amount': 1, 'unit': 'whole'},
            {'name': 'Dried Currants', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Heavy Cream', 'amount': 0.25, 'unit': 'cup'}
        ],
        'instructions': '1. Mix dry ingredients.\n2. Cut in butter.\n3. Mix in milk and egg.\n4. Fold in currants.\n5. Pat into circle and cut.\n6. Brush with cream.\n7. Bake at 400°F for 15-18 minutes.',
        'prep_time': 20,
        'cook_time': 18,
        'total_time': 38,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'British',
        'meal_type': 'Breakfast',
        'calories': 280,
        'protein': 5,
        'carbs': 42,
        'fat': 10,
        'fiber': 1,
        'sugar': 12,
        'rating': 4.6,
        'review_count': 320
    },
    {
        'name': 'Chocolate Cheesecake',
        'description': 'Rich and creamy chocolate cheesecake with chocolate crust',
        'ingredients': [
            {'name': 'Chocolate Cookies', 'amount': 2, 'unit': 'cups'},
            {'name': 'Melted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Cream Cheese', 'amount': 24, 'unit': 'ounces'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Dark Chocolate', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Cocoa Powder', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 3, 'unit': 'whole'},
            {'name': 'Heavy Cream', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Make cookie crust.\n2. Beat cream cheese and sugar.\n3. Melt chocolate and mix with cocoa.\n4. Add eggs one at a time.\n5. Pour into crust.\n6. Bake in water bath at 325°F for 1 hour.\n7. Cool and chill.',
        'prep_time': 30,
        'cook_time': 60,
        'total_time': 90,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 460,
        'protein': 8,
        'carbs': 38,
        'fat': 32,
        'fiber': 2,
        'sugar': 28,
        'rating': 4.9,
        'review_count': 780
    },
    {
        'name': 'Pavlova',
        'description': 'Light and airy meringue dessert with fresh fruit',
        'ingredients': [
            {'name': 'Egg Whites', 'amount': 4, 'unit': 'large'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cornstarch', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'White Vinegar', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Heavy Cream', 'amount': 1, 'unit': 'cup'},
            {'name': 'Fresh Berries', 'amount': 2, 'unit': 'cups'},
            {'name': 'Powdered Sugar', 'amount': 2, 'unit': 'tablespoons'}
        ],
        'instructions': '1. Beat egg whites until soft peaks.\n2. Gradually add sugar.\n3. Fold in cornstarch, vinegar, vanilla.\n4. Shape and bake at 250°F for 1.5 hours.\n5. Cool completely.\n6. Top with whipped cream and fruit.',
        'prep_time': 30,
        'cook_time': 90,
        'total_time': 120,
        'servings': 8,
        'difficulty': 'Hard',
        'cuisine_type': 'Australian',
        'meal_type': 'Dessert',
        'calories': 220,
        'protein': 2,
        'carbs': 42,
        'fat': 4,
        'fiber': 1,
        'sugar': 38,
        'rating': 4.8,
        'review_count': 450
    },
    {
        'name': 'Black Forest Cake',
        'description': 'German chocolate cake with cherries and whipped cream',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Cocoa Powder', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Baking Soda', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 2, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 3, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Sour Cream', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Hot Coffee', 'amount': 1, 'unit': 'cup'},
            {'name': 'Cherry Pie Filling', 'amount': 2, 'unit': 'cups'},
            {'name': 'Heavy Cream', 'amount': 2, 'unit': 'cups'},
            {'name': 'Dark Chocolate', 'amount': 4, 'unit': 'ounces'}
        ],
        'instructions': '1. Make chocolate cake layers.\n2. Make whipped cream.\n3. Layer cake with cherries and cream.\n4. Garnish with chocolate shavings.',
        'prep_time': 45,
        'cook_time': 35,
        'total_time': 80,
        'servings': 12,
        'difficulty': 'Hard',
        'cuisine_type': 'German',
        'meal_type': 'Dessert',
        'calories': 480,
        'protein': 6,
        'carbs': 58,
        'fat': 26,
        'fiber': 3,
        'sugar': 42,
        'rating': 4.9,
        'review_count': 720
    },
    {
        'name': 'Madeleines',
        'description': 'Classic French butter cakes with shell-like shape',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 1, 'unit': 'cup'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Granulated Sugar', 'amount': 0.67, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Lemon Zest', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Powdered Sugar', 'amount': 0.25, 'unit': 'cup'}
        ],
        'instructions': '1. Brown butter and cool.\n2. Beat eggs and sugar until pale.\n3. Fold in flour mixture.\n4. Stir in butter and zest.\n5. Chill batter.\n6. Bake in madeleine pan at 375°F for 11-13 minutes.',
        'prep_time': 20,
        'cook_time': 12,
        'total_time': 32,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'French',
        'meal_type': 'Dessert',
        'calories': 160,
        'protein': 2,
        'carbs': 18,
        'fat': 9,
        'fiber': 0,
        'sugar': 12,
        'rating': 4.7,
        'review_count': 380
    },
    {
        'name': 'Cream Puffs',
        'description': 'Light and airy choux pastry filled with cream',
        'ingredients': [
            {'name': 'Water', 'amount': 1, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'All Purpose Flour', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 4, 'unit': 'whole'},
            {'name': 'Heavy Cream', 'amount': 2, 'unit': 'cups'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Powdered Sugar', 'amount': 0.25, 'unit': 'cup'}
        ],
        'instructions': '1. Boil water, butter, salt.\n2. Add flour all at once.\n3. Cook and stir until it forms a ball.\n4. Beat in eggs one at a time.\n5. Pipe onto baking sheet.\n6. Bake at 400°F for 25-30 minutes.\n7. Fill with whipped cream.',
        'prep_time': 30,
        'cook_time': 30,
        'total_time': 60,
        'servings': 24,
        'difficulty': 'Hard',
        'cuisine_type': 'French',
        'meal_type': 'Dessert',
        'calories': 140,
        'protein': 2,
        'carbs': 8,
        'fat': 11,
        'fiber': 0,
        'sugar': 4,
        'rating': 4.8,
        'review_count': 560
    },
    {
        'name': 'Sticky Toffee Pudding',
        'description': 'Moist date cake with warm toffee sauce',
        'ingredients': [
            {'name': 'Dates', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Hot Water', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Baking Soda', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'All Purpose Flour', 'amount': 1.75, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Dark Brown Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Heavy Cream', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Light Brown Sugar', 'amount': 1, 'unit': 'cup'}
        ],
        'instructions': '1. Soak dates in hot water with baking soda.\n2. Make cake batter.\n3. Fold in date mixture.\n4. Bake at 350°F for 35-40 minutes.\n5. Make toffee sauce.\n6. Pour over warm cake.',
        'prep_time': 30,
        'cook_time': 40,
        'total_time': 70,
        'servings': 9,
        'difficulty': 'Medium',
        'cuisine_type': 'British',
        'meal_type': 'Dessert',
        'calories': 420,
        'protein': 4,
        'carbs': 68,
        'fat': 16,
        'fiber': 2,
        'sugar': 52,
        'rating': 4.9,
        'review_count': 480
    },
    {
        'name': 'French Macarons',
        'description': 'Delicate almond meringue cookies with filling',
        'ingredients': [
            {'name': 'Almond Flour', 'amount': 1.75, 'unit': 'cups'},
            {'name': 'Powdered Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Egg Whites', 'amount': 3, 'unit': 'large'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Cream Cheese', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Butter', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Food Coloring', 'amount': 1, 'unit': 'drop'}
        ],
        'instructions': '1. Sift almond flour and powdered sugar.\n2. Make French meringue.\n3. Fold dry into meringue.\n4. Pipe rounds.\n5. Rest until skin forms.\n6. Bake at 300°F for 15-17 minutes.\n7. Make filling.\n8. Fill and mature overnight.',
        'prep_time': 60,
        'cook_time': 17,
        'total_time': 77,
        'servings': 24,
        'difficulty': 'Hard',
        'cuisine_type': 'French',
        'meal_type': 'Dessert',
        'calories': 90,
        'protein': 2,
        'carbs': 12,
        'fat': 4,
        'fiber': 1,
        'sugar': 10,
        'rating': 4.7,
        'review_count': 890
    },
    {
        'name': 'Cinnamon Sugar Donuts',
        'description': 'Classic baked donuts with cinnamon sugar coating',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Baking Soda', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Ground Nutmeg', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Granulated Sugar', 'amount': 0.67, 'unit': 'cup'},
            {'name': 'Melted Butter', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Milk', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'tablespoon'}
        ],
        'instructions': '1. Mix dry ingredients.\n2. Whisk wet ingredients.\n3. Combine wet and dry.\n4. Fill donut pan.\n5. Bake at 350°F for 10-12 minutes.\n6. Coat in cinnamon sugar.',
        'prep_time': 20,
        'cook_time': 12,
        'total_time': 32,
        'servings': 12,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Breakfast',
        'calories': 220,
        'protein': 3,
        'carbs': 36,
        'fat': 7,
        'fiber': 1,
        'sugar': 18,
        'rating': 4.8,
        'review_count': 920
    },
    {
        'name': 'Hot Cross Buns',
        'description': 'Traditional spiced Easter buns with crosses',
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Warm Milk', 'amount': 1.25, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Ground Nutmeg', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Ground Allspice', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Raisins', 'amount': 1, 'unit': 'cup'},
            {'name': 'Orange Zest', 'amount': 1, 'unit': 'tablespoon'}
        ],
        'instructions': '1. Proof yeast in warm milk.\n2. Mix dough ingredients.\n3. Knead until smooth.\n4. Let rise until doubled.\n5. Shape into buns.\n6. Pipe crosses.\n7. Bake at 375°F for 20-25 minutes.\n8. Glaze while warm.',
        'prep_time': 120,
        'cook_time': 25,
        'total_time': 145,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'British',
        'meal_type': 'Breakfast',
        'calories': 240,
        'protein': 6,
        'carbs': 44,
        'fat': 5,
        'fiber': 2,
        'sugar': 14,
        'rating': 4.7,
        'review_count': 450
    },
    {
        'name': 'Chocolate Chip Muffins',
        'description': 'Bakery-style muffins loaded with chocolate chips',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.5, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Baking Soda', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Sour Cream', 'amount': 1, 'unit': 'cup'},
            {'name': 'Milk', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Chocolate Chips', 'amount': 1.5, 'unit': 'cups'}
        ],
        'instructions': '1. Mix dry ingredients.\n2. Cream butter and sugar.\n3. Add eggs and vanilla.\n4. Alternate dry ingredients with sour cream and milk.\n5. Fold in chocolate chips.\n6. Fill muffin cups.\n7. Bake at 425°F for 5 minutes.\n8. Reduce to 350°F for 15 minutes.',
        'prep_time': 20,
        'cook_time': 20,
        'total_time': 40,
        'servings': 12,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Breakfast',
        'calories': 320,
        'protein': 5,
        'carbs': 44,
        'fat': 16,
        'fiber': 2,
        'sugar': 26,
        'rating': 4.8,
        'review_count': 780
    },
    {
        'name': 'Apple Turnovers',
        'description': 'Flaky pastries filled with cinnamon apple',
        'ingredients': [
            {'name': 'Puff Pastry', 'amount': 2, 'unit': 'sheets'},
            {'name': 'Apples', 'amount': 3, 'unit': 'large'},
            {'name': 'Brown Sugar', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Ground Cinnamon', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Ground Nutmeg', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Lemon Juice', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Cornstarch', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Large Egg', 'amount': 1, 'unit': 'whole'},
            {'name': 'Water', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Coarse Sugar', 'amount': 2, 'unit': 'tablespoons'}
        ],
        'instructions': '1. Cook apple filling.\n2. Cool completely.\n3. Cut pastry into squares.\n4. Fill and seal edges.\n5. Brush with egg wash.\n6. Sprinkle with sugar.\n7. Bake at 400°F for 20-25 minutes.',
        'prep_time': 30,
        'cook_time': 25,
        'total_time': 55,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 280,
        'protein': 3,
        'carbs': 36,
        'fat': 14,
        'fiber': 2,
        'sugar': 16,
        'rating': 4.7,
        'review_count': 560
    },
    {
        'name': 'Sugar Cookies',
        'description': 'Classic soft and chewy sugar cookies',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 3, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Unsalted Butter', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'}
        ],
        'instructions': '1. Cream butter and sugar.\n2. Beat in eggs and vanilla.\n3. Mix in dry ingredients.\n4. Chill dough.\n5. Roll and cut shapes.\n6. Bake at 350°F for 10-12 minutes.',
        'prep_time': 30,
        'cook_time': 12,
        'total_time': 42,
        'servings': 24,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 120,
        'protein': 1,
        'carbs': 15,
        'fat': 6,
        'fiber': 0,
        'sugar': 8,
        'rating': 4.8,
        'review_count': 1200
    },
    {
        'name': 'Banana Bread',
        'description': 'Moist and flavorful classic banana bread',
        'ingredients': [
            {'name': 'Ripe Bananas', 'amount': 3, 'unit': 'large'},
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Baking Soda', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Sour Cream', 'amount': 0.33, 'unit': 'cup'}
        ],
        'instructions': '1. Mash bananas.\n2. Cream butter and sugar.\n3. Beat in eggs and vanilla.\n4. Mix in dry ingredients and sour cream.\n5. Fold in bananas.\n6. Bake at 350°F for 60-65 minutes.',
        'prep_time': 15,
        'cook_time': 65,
        'total_time': 80,
        'servings': 12,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Breakfast',
        'calories': 220,
        'protein': 3,
        'carbs': 34,
        'fat': 8,
        'fiber': 1,
        'sugar': 18,
        'rating': 4.9,
        'review_count': 2500
    },
    {
        'name': 'Dinner Rolls',
        'description': 'Soft and fluffy homemade dinner rolls',
        'ingredients': [
            {'name': 'Bread Flour', 'amount': 4, 'unit': 'cups'},
            {'name': 'Active Dry Yeast', 'amount': 2.25, 'unit': 'teaspoons'},
            {'name': 'Warm Milk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Unsalted Butter', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Salt', 'amount': 1.5, 'unit': 'teaspoons'}
        ],
        'instructions': '1. Proof yeast in warm milk.\n2. Mix dough ingredients.\n3. Knead until smooth.\n4. Let rise until doubled.\n5. Shape into rolls.\n6. Let rise again.\n7. Bake at 375°F for 15-20 minutes.',
        'prep_time': 120,
        'cook_time': 20,
        'total_time': 140,
        'servings': 15,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Bread',
        'calories': 160,
        'protein': 4,
        'carbs': 26,
        'fat': 5,
        'fiber': 1,
        'sugar': 2,
        'rating': 4.8,
        'review_count': 950
    },
    {
        'name': 'Pecan Pie',
        'description': 'Rich and gooey Southern pecan pie',
        'ingredients': [
            {'name': 'Pie Crust', 'amount': 1, 'unit': 'whole'},
            {'name': 'Pecans', 'amount': 2, 'unit': 'cups'},
            {'name': 'Dark Corn Syrup', 'amount': 1, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 3, 'unit': 'whole'},
            {'name': 'Brown Sugar', 'amount': 0.67, 'unit': 'cup'},
            {'name': 'Melted Butter', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Prepare pie crust.\n2. Mix filling ingredients.\n3. Add pecans.\n4. Pour into crust.\n5. Bake at 375°F for 40-50 minutes.',
        'prep_time': 20,
        'cook_time': 50,
        'total_time': 70,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 520,
        'protein': 6,
        'carbs': 64,
        'fat': 28,
        'fiber': 2,
        'sugar': 48,
        'rating': 4.9,
        'review_count': 880
    },
    {
        'name': 'Strawberry Shortcake',
        'description': 'Classic dessert with fresh strawberries and whipped cream',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.33, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'tablespoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Granulated Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Cold Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Heavy Cream', 'amount': 1, 'unit': 'cup'},
            {'name': 'Fresh Strawberries', 'amount': 4, 'unit': 'cups'},
            {'name': 'Powdered Sugar', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Make biscuit dough.\n2. Cut and bake biscuits.\n3. Prepare strawberries.\n4. Whip cream.\n5. Assemble shortcakes.\n6. Serve immediately.',
        'prep_time': 30,
        'cook_time': 15,
        'total_time': 45,
        'servings': 8,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 380,
        'protein': 4,
        'carbs': 46,
        'fat': 22,
        'fiber': 2,
        'sugar': 24,
        'rating': 4.8,
        'review_count': 760
    },
    {
        'name': 'Chocolate Cupcakes',
        'description': 'Moist chocolate cupcakes with chocolate frosting',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Cocoa Powder', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Baking Powder', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Baking Soda', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Granulated Sugar', 'amount': 1.5, 'unit': 'cups'},
            {'name': 'Vegetable Oil', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'},
            {'name': 'Buttermilk', 'amount': 1, 'unit': 'cup'},
            {'name': 'Hot Coffee', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Powdered Sugar', 'amount': 4, 'unit': 'cups'}
        ],
        'instructions': '1. Mix dry ingredients.\n2. Beat wet ingredients.\n3. Combine wet and dry.\n4. Add hot coffee.\n5. Fill cupcake liners.\n6. Bake at 350°F for 18-20 minutes.\n7. Make frosting.\n8. Frost cooled cupcakes.',
        'prep_time': 30,
        'cook_time': 20,
        'total_time': 50,
        'servings': 24,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 280,
        'protein': 3,
        'carbs': 42,
        'fat': 12,
        'fiber': 2,
        'sugar': 32,
        'rating': 4.9,
        'review_count': 1500
    },
    {
        'name': 'Gingerbread Cookies',
        'description': 'Spiced holiday cookies perfect for decorating',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 3, 'unit': 'cups'},
            {'name': 'Ground Ginger', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Ground Cinnamon', 'amount': 1.5, 'unit': 'teaspoons'},
            {'name': 'Baking Soda', 'amount': 0.75, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Butter', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 0.75, 'unit': 'cup'},
            {'name': 'Large Egg', 'amount': 1, 'unit': 'whole'},
            {'name': 'Molasses', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Powdered Sugar', 'amount': 2, 'unit': 'cups'}
        ],
        'instructions': '1. Mix dry ingredients.\n2. Cream butter and sugar.\n3. Add egg and molasses.\n4. Mix in dry ingredients.\n5. Chill dough.\n6. Roll and cut shapes.\n7. Bake at 350°F for 8-10 minutes.\n8. Decorate with icing.',
        'prep_time': 45,
        'cook_time': 10,
        'total_time': 55,
        'servings': 24,
        'difficulty': 'Medium',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 160,
        'protein': 2,
        'carbs': 26,
        'fat': 6,
        'fiber': 1,
        'sugar': 14,
        'rating': 4.8,
        'review_count': 920
    },
    {
        'name': 'Cheese Danish',
        'description': 'Flaky pastry filled with sweet cream cheese',
        'ingredients': [
            {'name': 'Puff Pastry', 'amount': 2, 'unit': 'sheets'},
            {'name': 'Cream Cheese', 'amount': 8, 'unit': 'ounces'},
            {'name': 'Granulated Sugar', 'amount': 0.33, 'unit': 'cup'},
            {'name': 'Large Egg', 'amount': 1, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Lemon Zest', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Egg Wash', 'amount': 1, 'unit': 'whole'},
            {'name': 'Powdered Sugar', 'amount': 0.5, 'unit': 'cup'}
        ],
        'instructions': '1. Make cheese filling.\n2. Cut pastry into squares.\n3. Add filling.\n4. Shape corners.\n5. Brush with egg wash.\n6. Bake at 400°F for 20-22 minutes.\n7. Dust with powdered sugar.',
        'prep_time': 25,
        'cook_time': 22,
        'total_time': 47,
        'servings': 12,
        'difficulty': 'Medium',
        'cuisine_type': 'Danish',
        'meal_type': 'Breakfast',
        'calories': 280,
        'protein': 5,
        'carbs': 28,
        'fat': 16,
        'fiber': 1,
        'sugar': 12,
        'rating': 4.7,
        'review_count': 640
    },
    {
        'name': 'Peanut Butter Cookies',
        'description': 'Classic crisscross peanut butter cookies',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2.5, 'unit': 'cups'},
            {'name': 'Baking Powder', 'amount': 1, 'unit': 'teaspoon'},
            {'name': 'Baking Soda', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'teaspoon'},
            {'name': 'Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Creamy Peanut Butter', 'amount': 1, 'unit': 'cup'},
            {'name': 'Brown Sugar', 'amount': 1, 'unit': 'cup'},
            {'name': 'Granulated Sugar', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Large Eggs', 'amount': 2, 'unit': 'whole'},
            {'name': 'Vanilla Extract', 'amount': 2, 'unit': 'teaspoons'}
        ],
        'instructions': '1. Cream butter, peanut butter, sugars.\n2. Beat in eggs and vanilla.\n3. Mix in dry ingredients.\n4. Roll into balls.\n5. Make crisscross pattern.\n6. Bake at 350°F for 10-12 minutes.',
        'prep_time': 20,
        'cook_time': 12,
        'total_time': 32,
        'servings': 36,
        'difficulty': 'Easy',
        'cuisine_type': 'American',
        'meal_type': 'Dessert',
        'calories': 120,
        'protein': 3,
        'carbs': 14,
        'fat': 7,
        'fiber': 1,
        'sugar': 8,
        'rating': 4.8,
        'review_count': 1100
    },
    {
        'name': 'Garlic Bread',
        'description': 'Crusty bread with garlic butter and herbs',
        'ingredients': [
            {'name': 'French Bread', 'amount': 1, 'unit': 'loaf'},
            {'name': 'Butter', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Garlic Cloves', 'amount': 4, 'unit': 'whole'},
            {'name': 'Fresh Parsley', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Parmesan Cheese', 'amount': 0.25, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 0.25, 'unit': 'teaspoon'},
            {'name': 'Black Pepper', 'amount': 0.25, 'unit': 'teaspoon'}
        ],
        'instructions': '1. Mix garlic butter.\n2. Cut bread lengthwise.\n3. Spread butter mixture.\n4. Sprinkle with cheese.\n5. Bake at 400°F for 10-15 minutes.',
        'prep_time': 10,
        'cook_time': 15,
        'total_time': 25,
        'servings': 8,
        'difficulty': 'Easy',
        'cuisine_type': 'Italian',
        'meal_type': 'Bread',
        'calories': 220,
        'protein': 5,
        'carbs': 24,
        'fat': 12,
        'fiber': 1,
        'sugar': 1,
        'rating': 4.8,
        'review_count': 850
    }
]

def create_sample_database():
    """Create a sample database with common recipes"""
    db_path = os.path.join(os.path.dirname(__file__), 'recipes.db')
    
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Create recipes table
        cursor.execute('''
        CREATE TABLE IF NOT EXISTS recipes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            instructions TEXT NOT NULL,
            prep_time INTEGER,
            cook_time INTEGER,
            total_time INTEGER,
            servings INTEGER,
            difficulty TEXT,
            cuisine_type TEXT,
            meal_type TEXT,
            calories REAL,
            protein REAL,
            carbs REAL,
            fat REAL,
            fiber REAL,
            sugar REAL,
            rating REAL,
            review_count INTEGER
        )
        ''')
        
        # Create ingredients table
        cursor.execute('''
        CREATE TABLE IF NOT EXISTS ingredients (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            recipe_id INTEGER,
            name TEXT NOT NULL,
            amount REAL,
            unit TEXT,
            FOREIGN KEY (recipe_id) REFERENCES recipes (id)
        )
        ''')
        
        # Clear existing data
        cursor.execute('DELETE FROM ingredients')
        cursor.execute('DELETE FROM recipes')
        
        # Insert sample recipes
        for recipe in SAMPLE_RECIPES:
            cursor.execute('''
            INSERT INTO recipes (
                name, description, instructions, prep_time, cook_time, total_time,
                servings, difficulty, cuisine_type, meal_type, calories, protein,
                carbs, fat, fiber, sugar, rating, review_count
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                recipe['name'], recipe['description'], recipe['instructions'],
                recipe['prep_time'], recipe['cook_time'], recipe['total_time'],
                recipe['servings'], recipe['difficulty'], recipe['cuisine_type'],
                recipe['meal_type'], recipe['calories'], recipe['protein'],
                recipe['carbs'], recipe['fat'], recipe['fiber'], recipe['sugar'],
                recipe['rating'], recipe['review_count']
            ))
            
            recipe_id = cursor.lastrowid
            
            # Insert ingredients
            for ingredient in recipe['ingredients']:
                cursor.execute('''
                INSERT INTO ingredients (recipe_id, name, amount, unit)
                VALUES (?, ?, ?, ?)
                ''', (recipe_id, ingredient['name'], ingredient['amount'], ingredient['unit']))
        
        conn.commit()
        logger.info(f"Created sample database with {len(SAMPLE_RECIPES)} recipes at {db_path}")
        
    except Exception as e:
        logger.error(f"Error creating sample database: {e}")
        raise
    finally:
        conn.close()

if __name__ == '__main__':
    create_sample_database()
